### ISSUE TITLE
Suggestions for resources page

### ISSUE THREAD

**Issue by emiliagogu** [ismir/ismir_web#15]
It would be nice to add to the web page, http://ismir.net/resources.html#educational-materials, this one 

http://mtg.upf.edu/mir-tutorial
http://www.nowpublishers.com/article/Details/INR-042 (free)
https://www.audiolabs-erlangen.de/fau/professor/mueller/bookFMP

Please let me know if I should edit it through github.

e

**Comment by ybayle** [comment]
I think this issue can be closed or merged to #19 ?

**Comment by ejhumphrey** [comment]
merging with #19 is a great idea, i'll copy the links above over for posterity and close this.
