### ISSUE TITLE
Enables public access to the MIR Slack

### ISSUE THREAD

**Issue by ybayle** [ismir/ismir_web#17]
Dear ISMIR team,

Thanks to Eric Robinson, we can now have beautiful conversations on Slack. Unfortunately, it is not straightforward for new users to join this Slack. Would it be possible to had this [https://github.com/loretoparisi/slackin](https://github.com/loretoparisi/slackin) to the ismir website?

Thank you,
Yann

**Comment by ericdrobinson** [comment]
Another option would be to use the [Stacktodo Invite Bot](http://signup.team/tools/invite) service, which appears to be free. This creates a landing page that is hosted and run on the Stacktodo servers. At the very least, adding a link from the ISMIR site to the MIR Slack Community would be nice.

**Comment by woodshop** [comment]
Hello Yann and Eric, Sorry for the delay. We've having an internal conversation about Slack. Who os the current administrator of the community?

**Comment by ericdrobinson** [comment]
>Who os the current administrator of the community?
@woodshop That would be me!

As a side note, it appears that Stacktodo isn't super responsive. Currently investigating [SlackPass](https://slackpass.io/) for an open sign up service instead.

**Comment by ericdrobinson** [comment]
The SlackPass signup page is up. Check it out [here](https://slackpass.io/mircommunity). At the very least, a link may work? Am open to discussing the whole approach, too, of course!

**Comment by ybayle** [comment]
Would it be better to have:

- an iframe integrating the link on ismir.net or
- an external link pointing to it?

**Comment by ejhumphrey** [comment]
are iframes still used? I was under the poorly informed impression that iframes have fallen out of practice. regardless, an external link with a nice PNG badge might be nice?

**Comment by ybayle** [comment]
Ok, maybe we could go for a button/link with an official badge [like this](https://slack.com/brand-guidelines) in the footer? Or is it necessary to have a supplementary tab in the menu on the left?

**Comment by ejhumphrey** [comment]
this is fixed with #18
