### ISSUE TITLE
Resources page appearance

### ISSUE THREAD

**Issue by ybayle** [ismir/ismir_web#19]
I made multiple MIR-related lists that I wanted to add on my website. However, I think it would be better instead to enhance the already existing lists on [http://www.ismir.net/resources.html](http://www.ismir.net/resources.html). Unfortunately, adding a lot of material would make the resources page looks messy and too big. I would like to suggest 2 ideas to overcome this:
1. Add a [dropdown](http://getbootstrap.com/components/#dropdowns) to the menu with one page per type of resources
2. Keep one resources page but use [tabs](http://getbootstrap.com/components/#nav-tabs)

If you think this is not a problem to have a lot of links, I would still be happy to make a pull request with all my links.

**Comment by woodshop** [comment]
Admittedly the resources page is already messy and too big. How many additional resources would you like to add? Would you be interested in creating a pull request with a dropdown menu?

**Comment by ybayle** [comment]
> Would you be interested in creating a pull request with a dropdown menu?

I will create a pull request with a dropdown menu. We could then discuss on the visual aspect of it.

> How many additional resources would you like to add? 

I have multiple links in multiple categories to add:

- ~10 MIR courses / Educational Materials
- ~3 Research Centers
- ~5 Related Conferences and Journals
- ~5 Software Tools
- ~3 Plagiarism helpful link
- ~60 musical streaming website 
- ~10 MIR GitHub
- ~3 MIR reproducible ressources and tools

Concerning the datasets, there is an exhaustive list provided here [http://www.audiocontentanalysis.org/data-sets/](http://www.audiocontentanalysis.org/data-sets/). The question is, is it better to have an external link pointing to this website or to integrate the list on ismir.net (and adding complementary info) to guarantee posteriority?

**Comment by ejhumphrey** [comment]
awesome, thanks for the help! 👍 

in case it's not already on your radar, I suppose we'll want to make sure the site still work on mobile (no rollovers)? just a thought

**Comment by ejhumphrey** [comment]
EG's original links 
http://mtg.upf.edu/mir-tutorial
http://www.nowpublishers.com/article/Details/INR-042 (free)
https://www.audiolabs-erlangen.de/fau/professor/mueller/bookFMP

**Comment by ejhumphrey** [comment]
fixed via #18
