### ISSUE TITLE
Update ISMIR board information

### ISSUE THREAD

**Issue by emiliagogu** [ismir/ismir_web#26]
We should update ISMIR board information for 2018-2019.

**Comment by emiliagogu** [comment]
=Officers ISMIR Board 2018-2019=
President: Emilia Gómez, Universitat Pompeu Fabra, Spain
President-elect: Meinard Müller, International Audio Laboratories
Erlangen, Germany
Secretary: Eric J. Humphrey, Spotify, USA
Treasurer: Bob Sturm, QMUL, UK
Member-at-large: Geoffroy Peeters, IRCAM, France
Member-at-large: Blair Kaneshiro, Stanford U., USA
Member-at-large: Douglas Turnbull, Ithaca College
Student member: Iris Yuping Ren, Utrecht U., Netherlands

**Comment by ejhumphrey** [comment]
not sure when this was updated, but it's all set now
